FROM node:18 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install || true

COPY client ./client

COPY shared ./shared

RUN cp -r /app/shared /app/client/shared

WORKDIR /app/client

RUN npm install

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/client/dist /usr/share/nginx/html

COPY client/.gitignore ./

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
