FROM node:18

WORKDIR /app/server

COPY server/ ./

COPY shared/ ../shared/

COPY config.js /app/server/config.js

# COPY server/.gitignore ./

RUN npm install

RUN npm install -g nodemon

RUN npm install --save-dev nodemon

EXPOSE 5000

CMD ["nodemon", "index.js"]